### ISSUE TITLE
Misleading of sparsity-promoting function

### ISSUE THREAD

**Issue by Bowenwu1** [yuxwind/epsilon-resnet#1]
https://github.com/yuxwind/epsilonResnet/blob/master/scripts/EpsilonResnetBase.py#L26

The paper didn't mention the use of `reduce_max` which make the description of sparsity-promoting function not self-alignment.

More specifically, your paper didn't describe how 'return 0.0 only if the absolute values of all elemenents in l are smaller than EPSILON' is implemented.

**Comment by yuxwind** [comment]
-About reduce_max: 
You might have noted that the comparison between  _**all**_ the elements in a tensor and _EPSILON_ returns a single value 0/1 in the _sparsity-promoting function_, which is a dimension reduction operation. Reduce_max() can make it. You are free to try other Tensorflow operations, such as reduce_sum() in L26 of the code. As there are many ways, we didn't specify it in the paper.

-How to return 0.0 only if the absolute values of all elements in l are smaller than _EPSILON_?
As described in the paragraph "Proposed Structure", 

> First, let us consider the case when all the response elements satisfy the condition |F(x)i| < EPSILON. In this case, the output from the summation (+) will be zero. A zero input to the third RELU will lead to an output of 1. An output of 1 from the third RELU will lead to an output of 0 from the fourth RELU. Finally, we will have T (F(x)) = 0
